# Generated by Django 5.1.4 on 2024-12-30 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdatas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffiles',
            name='file',
            field=models.FileField(unique=True, upload_to='pdffiles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
