# Generated by Django 5.1.4 on 2024-12-31 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdatas', '0002_alter_pdffiles_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='pdffiles',
            name='file',
            field=models.FileField(upload_to='pdffiles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterUniqueTogether(
            name='pdffiles',
            unique_together={('file',)},
        ),
    ]
