# Generated by Django 5.1.4 on 2024-12-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdatas', '0003_employee_alter_pdffiles_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
